name: Update data

on:
  schedule:
    - cron: "00 00 * * *"
      timezone: Europe/London

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Update data
      run: |
        python -c "
        from currencyexchange.model import CEModel
        model = CEModel()
        model.set_data()
        "
