name: Update data

on:
  push:
    branches:
      - master
      - workflow
  
  schedule:
    - cron: "10 0 * * *"
      timezone: Europe/London

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Update data
      run: |
        python -c "
        from currencyexchange.model import CEModel
        model = CEModel()
        model.set_data('${{ secrets.API_KEY }}')
        "
     
    - name: Add and commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Update data"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
